provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  of-barcode-generator:
    lang: node
    handler: ./barcode
    image: padiazg/of-barcode-generator
    environment:
      write_timeout: 10s
      read_timeout: 10s
