provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  barcode:
    lang: node
    handler: ./barcode
    image: padiazg/barcode
    environment:
      write_timeout: 10s
      read_timeout: 10s
